# SPDX-FileCopyrightText: 2023 meson-python developers
#
# SPDX-License-Identifier: MIT

version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements: [docs]
