# SPDX-FileCopyrightText: 2023 meson-python developers
#
# SPDX-License-Identifier: MIT

comment: false
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
