name: checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mypy:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install mypy
        run: python -m pip --disable-pip-version-check install mypy==0.981

      - name: Run mypy
        run: mypy -p mesonpy
